### ISSUE TITLE
adding a way to change which reactions are associated with which species 

### ISSUE THREAD

**Issue by dalbabur** [adelhpour/SBMLNetwork#103]
I'd like to be able to see and change which reactions are connected to each species / aliasSpecies. maybe something like 
SBMLNW.getSpeciesReactions(species, index) -> list of the reactions and indexes connected to this AliasSpecies
SBMLNW.moveReaction(reaction, index, old_species, old_species_index, new_species_index)

**Comment by adelhpour** [comment]
The feature is added in this https://github.com/sys-bio/SBMLNetwork/pull/3. Thanks for the contribution!
