### ISSUE TITLE
Hiding species

### ISSUE THREAD

**Issue by mkcook** [adelhpour/SBMLNetwork#104]
I want to be able to hide certain species and the lines associated with their reactions. A use case of this is hiding the cofactors or otherwise secondary substrates and products of a reaction, but keeping the primary substrate and product. Also, presumably this would need to be specified by index so it didn't erase other instances of the same species in other locations.

**Comment by adelhpour** [comment]
The feature is added in this [PR](https://github.com/sys-bio/SBMLNetwork/pull/3). Thanks for the contribution!
