### ISSUE TITLE
setSpeciesReferenceCurveSegmentStartPointX doesn't match in .h vs. .cpp

### ISSUE THREAD

**Issue by luciansmith** [adelhpour/SBMLNetwork#30]
'double x' vs. 'const double& x'

**Comment by luciansmith** [comment]
Same for 'setSpeciesReferenceCurveSegmentStartPointY'

**Comment by luciansmith** [comment]
setSpeciesReferenceCurveSegmentEndPointX (x1)
setSpeciesReferenceCurveSegmentEndPointY (x2)
setSpeciesReferenceCurveSegmentBasePoint1X (x2)
getSpeciesReferenceCurveSegmentBasePoint1Y (x1)
setSpeciesReferenceCurveSegmentBasePoint1Y (x2)
getSpeciesReferenceCurveSegmentBasePoint2X (x1)
setSpeciesReferenceCurveSegmentBasePoint2X (x2)
setSpeciesReferenceCurveSegmentBasePoint2Y (x2)
getText (x1)
setGraphicalObjectId

If you open the project in Visual Studio, it'll highlight all the mismatched functions in green.

**Comment by adelhpour** [comment]
Fixed with PR #31
