### ISSUE TITLE
Create .h file that includes everything

### ISSUE THREAD

**Issue by luciansmith** [adelhpour/SBMLNetwork#34]
It would be nice if I could just #include a single file and pull in the entire API.

**Comment by adelhpour** [comment]
@luciansmith if you are using the c_api, you just need to include "libsbmlnetwork_c_api.h".

The previous release had a bug, so it didn't copy 'c_api' directory under the include directory. It is now fixed with the latest [release](https://github.com/adelhpour/SBMLNetwork/releases/tag/v0.0.23).

**Comment by adelhpour** [comment]
To use C++ code, you can #include the followings to have access to all the functionalities:
#include "libsbmlnetwork_sbmldocument.h"
#include "libsbmlnetwork_sbmldocument_layout.h"
#include "libsbmlnetwork_sbmldocument_render.h"

I tried to decouple put the functions into three categories, sbmldocument, sbmldocument + layout, and sbmldocument  + render.
