### ISSUE TITLE
startHead and endHead types aren't validated

### ISSUE THREAD

**Issue by luciansmith** [adelhpour/SBMLNetwork#38]
There should be a fixed number of reaction head types that are validated.  I can't imagine that the spec literally allows free text here.

**Comment by luciansmith** [comment]
Although... it seems that they're IDs?  What?  I thought they were going to be things like 'arrow' and 'ball' or something.

**Comment by adelhpour** [comment]
They are  indeed the ids of the line endings in the render object.
