### ISSUE TITLE
AttributeError: 'SBMLNetwork' object has no attribute 'setGeometricShape'

### ISSUE THREAD

**Issue by sanast22** [adelhpour/SBMLNetwork#58]
I'm trying to change the shape of the species in my system and have previously used the setGeometricShape() method, but now I'm seeing an error that there is no such attribute. Is there a new way to change the shape of a species in the network?

Thanks!

**Comment by adelhpour** [comment]
Starting from version 0.1.2, we've replace 'setGeometricShape' with 'setGeometricShapeType' method. You can use the new version of it in your code with the same functionality!
