### ISSUE TITLE
Auto-layout

### ISSUE THREAD

**Issue by sanast22** [adelhpour/SBMLNetwork#61]
Is there a way to save an auto-layout that I like, and continue to set my model to that layout?

**Comment by adelhpour** [comment]
My suggestion would be to save the SBML model and load it again. you can use 'save' function and pass a file_name to it as an argument to save to your desired directory and file. Then, you can load it by passing the file_name as an argument to the 'load' file. Have you tried it before and looking for something different, or it is just the one you were looking for?

**Comment by sanast22** [comment]
Makes sense! I just noticed some auto-layouts that I liked more than others, so wanted to keep track of those.

**Comment by adelhpour** [comment]
The best you can do now is saving the SBML model of those you like and loading them again to continue working on them. Another thing that might be helpful is passing the 'locked_nodes' parameter to autolayout function. Just pass the id of the nodes you want to be fixed as a list to the autolayout function and then they won't move once the function is called again.
