### ISSUE TITLE
Labeling species

### ISSUE THREAD

**Issue by sanast22** [adelhpour/SBMLNetwork#62]
How can I hide all the names of species except a select few that I want to display? I see an option to display reaction text labeling with the enableDisplayReactionsTextLabel() method, but is there a similar method to display the names of each species?

**Comment by adelhpour** [comment]
There is not such an option to hide the label of the species, but that is actually a good Idea to add it. We'll work on it to add it to our next release.

**Comment by adelhpour** [comment]
We've added this feature and it will be available in our next release. Using this, it is possible to use enableDisplayCompartmentsTextLabel, enableDisplaySpeciesTextLabel, and enableDisplayReactionsTextLabel to turn displaying the labels on and off.
