### ISSUE TITLE
sbmlnetwork should update networkinfotranslator when pip installed

### ISSUE THREAD

**Issue by hsauro** [adelhpour/SBMLNetwork#76]
sbmlnetwork doesn't automatically update networkinfotranslator when pip install sbmlnetwork is called

**Comment by adelhpour** [comment]
The minimum required version of networkinfotranslator is put in the requirements of the sbmlnetwork. I would recommend using `pip install --upgrade sbmlnetwork` to update the package and its dependencies. Also, in some case you can call `pip uninstall sbmlnetwork` and then call `pip install sbmlnetwork` to make sure your old version is not causing  the issue.
