### ISSUE TITLE
Not sure if sb.getVersion() returns the current version.

### ISSUE THREAD

**Issue by hsauro** [adelhpour/SBMLNetwork#77]
I install sbmlnetwork

pip show sbmlnetwork

gives 0.1.2

but 

when I call

import sbmlnetwork
sb = sbmlnetwork.load ('c:\\tmp\\JanaWolf.xml')
sb.draw()
print (sb.getVersion())

I get 0.0.22

**Comment by adelhpour** [comment]
This is probably due to an issue of using an old version of sbmlnetwork on your machine. I tested it and it works fine now. Upgrading the sbmlnetwork using `pip install --upgrade sbmlnetwork` will probably solve the issue.
