### ISSUE TITLE
No means to make a gradient

### ISSUE THREAD

**Issue by hsauro** [adelhpour/SBMLNetwork#86]
There is currently no way to make a gradient to use on a for example a nodel

**Comment by adelhpour** [comment]
With merging PR #96, it is now possible to set the fill color of network elements with a gradient. Here is a simple example of its demonstration: 

```
import tellurium as te
import sbmlnetwork as sbmln

r = te.loada('''
S1 -> S2;
 ''')

network = sbmln.load(r.getSBML())
network.setFillColorAsGradient("S1", stop_colors=["blue", "red"], stop_offsets=[0, 100])
network.draw()
```
