### ISSUE TITLE
Access violation in setBorderColors

### ISSUE THREAD

**Issue by hsauro** [adelhpour/SBMLNetwork#88]
Call this and you'll get an access violation in setBorderColors

import tellurium as te
import sbmlnetwork

model = '''
var S0, S1, S2, S3, S4
J0: S1 -> S0 + S4; E0*(k0S1);
J1: S3 -> S4; E1(k1S3);
J2: S4 -> S3; E2(k2S4);
J3: S1 + S1 -> S3; E3(k3S1S1);
J4: S2 + S2 -> S0; E4*(k4S2S2);
J5: S0 -> S2 + S4; E5*(k5S0);
J6: S4 -> S1; E6(k6S4);
J7: S1 + S2 -> S3; E7(k7S1S2);
J8: S3 -> S1; E8*(k8*S3);

k0 = 0.182433; k1 = 0.150651; k2 = 0.153518;
k3 = 0.952991; k4 = 0.711677; k5 = 0.399124
k6 = 0.612890; k7 = 0.431755; k8 = 0.001688

E0 = 1; E1 = 1; E2 = 1; E3 = 1;
E4 = 1; E5 = 1; E6 = 1; E7 = 1
E8 = 1

S0 = 4; S1 = 5; S2 = 6; S3 = 6; S4 = 6
'''

r = te.loada (model)
sb = sbmlnetwork.load (r.getSBML())
sb.autolayout(4)

sb.setBorderColors('red', 1) # Anything above zero gives access violation

sb.draw()

**Comment by adelhpour** [comment]
Access violation bug is fixed with PR #96.
Note that the index you are passing is used as the index of the layout object of the SBMLDocument (and probably there is no  need to touch it for majority of models).
