### ISSUE TITLE
Put 'roundToTwoDecimalPlaces' back in at higher levels.

### ISSUE THREAD

**Issue by luciansmith** [adelhpour/SBMLNetwork#95]
The functions:

AutoLayoutNode::getX
AutoLayoutNode::getY
AutoLayoutNode::getWidth
AutoLayoutNode::getHeight

and

AutoLayoutCentroidNode::getX
AutoLayoutCentroidNode::getY
AutoLayoutCentroidNode::getWidth
AutoLayoutCentroidNode::getHeight

and

AutoLayoutPoint::getX
AutoLayoutPoint::getY

are all called extensively by the autolayout algorithm, and need to not waste time rounding values, as they're all called potentially thousands of times or more.  But we do still need to round off values when requesting them, so the 'round' function needs to be added back in at a higher level that autolayout doesn't call.

**Comment by adelhpour** [comment]
RoundToTwoDecimalNumber is moved to the libsbmlnetwork_layout layer with PR #97.
